version: '3.7'

services:

  mylovedb:
    container_name: mylovedb
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mylovedb
    networks:
      - default

  accountdb:
    container_name: accountdb
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=accountdb
    networks:
      - default
